#!/usr/bin/env bash

if [ -d ".venv" ]; then
    source .venv/bin/activate
else
    echo "No virtual environment found."
    exit 1
fi

python_files="chronicle/ tests/"

echo "Checking code format with Ruff..."
if ! ruff format --check ${python_files}; then
    ruff format --diff ${python_files}
    echo "FAIL"
    exit 1
fi

# echo "Checking types with mypy..."
# if ! mypy ${python_files}; then
#     echo "FAIL"
#     exit 1
# fi

echo "Linting with Ruff..."
if ! ruff check; then
    echo "FAIL"
    exit 1
fi

echo "Run pytest..."
pytest -v || { echo "FAIL"; exit 1; }

echo "OK"
