#!/usr/bin/env bash

python_files="chronicle tests"

echo "Checking code format with Black..."
if ! black -l 80 --check ${python_files}; then
    black -l 80 --diff --color ${python_files}
    echo "FAIL"
    exit 1
fi

# Link with Flake8.

echo "Lint with Flake8..."
flake8 \
    --max-line-length=80 \
    --ignore=ANN002,ANN003,ANN101,ANN102,E203,F403,F405,W503 \
    ${python_files} \
    || { echo "FAIL"; exit 1; }
