name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black~=23.1.0 flake8~=6.1.0 pytest
        pip install -r requirements.txt
    - name: Check code style with Black
      run: |
        black -l 80 --check chronicle tests
    - name: Lint with Flake8
      run: |
        flake8 --max-line-length=80 --ignore=ANN002,ANN003,ANN101,ANN102,E203,F403,F405,W503
    - name: Test with pytest
      run: |
        pytest -v
