name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Test with pytest
      run: |
        pytest -v

  check:
    name: Static Analysis, Code Style, Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Check Code Style with Ruff
      run: |
        ruff format --check chronicle/ tests/
    - name: Lint with Ruff
      run: |
        ruff check chronicle/ tests/
        ruff check --fix chronicle/ tests/

  lua-tests:
    name: Lua Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Lua
      uses: leafo/gh-actions-lua@v11
      with:
        luaVersion: '5.4'
    - name: Cache LuaRocks
      uses: actions/cache@v4
      with:
        path: ~/.cache/luarocks
        key: ${{ runner.os }}-luarocks-${{ hashFiles('**/rockspec') }}
        restore-keys: |
          ${{ runner.os }}-luarocks-
    - name: Install LuaUnit
      run: |
        luarocks config --local lua_version 5.4
        luarocks --local install luaunit
    - name: Run Lua tests
      env:
        LUA_PATH: "~/.luarocks/share/lua/5.4/?.lua;~/.luarocks/share/lua/5.4/?/init.lua;;"
        LUA_CPATH: "~/.luarocks/lib/lua/5.4/?.so;;"
      working-directory: scripts
      run: |
        lua test_chronicle.lua
