name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Test with pytest
      run: |
        pytest -v

  check:
    name: Static Analysis, Code Style, Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Check Code Style with Ruff
      run: |
        ruff format --check chronicle/ tests/
    - name: Lint with Ruff
      run: |
        ruff check chronicle/ tests/
        ruff check --fix chronicle/ tests/

  lua-tests:
    name: Lua Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: leafo/gh-actions-lua@v11
    - uses: leafo/gh-actions-luarocks@v5
    - name: Install LuaUnit
      run: |
        luarocks install luaunit
    - name: Run Lua tests
      working-directory: scripts
      run: |
        lua test_chronicle.lua
